export default {
    USER_RECEIVED: "USER_RECEIVED",
    OWNER_RECEIVED: "OWNER_RECIEVED",
    CLASSMATE_SELECTED: "CLASSMATE_SELECTED",
    STUDENT_PROFILE_RECIEVED: "STUDENT_PROFILE_RECIEVED",
   TEACHER_SELECTED: "TEACHER_SELECTED",
   SWITCHED_TO_TEACHING: "SWITCHED_TO_TEACHING"
  };